### ISSUE TITLE
Can you provide the basic structure of training data set?

### ISSUE THREAD

**Issue by sshzhang** [cronos123/CNN-with-Dual-Local-and-Global-Attention#1]
Hello author:
     I want to know the basic structure of data set . Can you provide for me ? Thanks a lot.

**Comment by seongjunyun** [comment]
Hi sshzhang,

Sorry for the late reply, I am not the original author and this code was a
test code for a personal project.

So please contact the original author for further information as full
credit goes to him.

Regards,
Seongjun

2018년 10월 11일 (목) 오후 8:37, sshzhang <notifications@github.com>님이 작성:
