### ISSUE TITLE
What is the shape of the user?

### ISSUE THREAD

**Issue by hyllll** [cronos123/CNN-with-Dual-Local-and-Global-Attention#2]
Hi author,
  What is the shape of the user which are inputted in your model? `outputs = CNNDLGA(user,item)`
Is the user's shape (batch_size, maxlen, embed_size) ?

**Comment by chaeheum3** [comment]
Hi hyllll,

Sorry for the late reply, we are not the original authors (Despite having similar name) and this code was a test code for a personal project.

So please contact the original author for further information as full credit goes to him.

Regards,
Chaeheum Park and Seongjun Yun
